[package]
name = "hdm_jam_jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bevy_proto = "0.5.0"
serde = "1.0.144"
typetag = "0.2"

# [dev-dependencies]
# rusty-hook = "0.11.2"
